#ifndef CHIP8_EMU_EMU_DEF_H
#define CHIP8_EMU_EMU_DEF_H

/*
 * Ram Locations
 */
#define EMU_RAM_ENTRY_POINT 0x200
#define EMU_CHIP8_MAX_PROG_RAM_ADDR (0xE90 - 1)
#define EMU_SUPER_CHIP8_MAX_PROG_RAM_ADDR (0xFFF - 1)

/*
 * Sizes
 */
#define EMU_CHIP_8_RAM_SIZE (0xFFF + 1)
#define EMU_CHIP8_MAX_ROM_SIZE (EMU_CHIP_8_RAM_SIZE - EMU_RAM_ENTRY_POINT)
#define EMU_CHIP_8_FONT_HEIGHT 5

/*
 * Other
 */
#define EMU_KEY_PRESSED 1
#define EMU_KEY_RELEASED 0
#define EMU_NB_FONTS 16

#endif // CHIP8_EMU_EMU_DEF_H
